### ISSUE TITLE
Doesn't always show up.

### ISSUE THREAD

**Issue by owldesign** [mmikkel/Reasons-Craft#7] opened 2015-09-24 20:21 UTC
I have a bunch of sections (structure, channel) and I noticed that for some of the the field layout designers the `manage conditionals` options doesn't show. I was trying to track down what could be the reasons but had no luck. 

For example I have 2 structure sections `news` and `events` for each I added the same fields in the field layout designer. I was able to get the 'manage conditionals' to show up for the `news`, but `events the option wasn't appearing. 

Anyone know if I'm missing something?

**Comment by mmikkel** [comment] 2015-09-25 09:16
Hello @owldesign, thanks for reporting.

I'm unable to reproduce this. Did you check the console/dev tools in your browser for JS errors? Also, which browser and OS are you using?

**Comment by owldesign** [comment] 2015-09-25 16:49
I'm on chrome mac. Here's a gif of whats happening. Notice the first section I click on doesn't even have a toggle field. The second one has toggle field `completed` but the drop down option isn't showing up. 

![example](https://cloud.githubusercontent.com/assets/438764/10106604/842643a8-636a-11e5-9f43-80fe2035cbf8.gif)

**Comment by mmikkel** [comment] 2015-09-26 05:54
Thanks for the gif, @owldesign! At first I figured "aha, it happens when there are multiple tabs", but no. Still not able to reproduce this.
1. You're positive there are no error messages in the browser console?
2. For the section that doesn't work, can you check if the Reasons JS is loaded? You're looking for a file called `FLD-d9b9c0756b326f51e93f.js`, see http://cly.mmikkel.no/image/0O0d3k2V3o3a
3. Did you test it in another browser?
4. If your data isn't too sensitive, you can send me an SQL dump and I'll replicate your site to test further – only on my local computer, and I promise to delete your data afterwards :)

**Comment by owldesign** [comment] 2015-09-28 18:12
I've tested on other browser. So it does looks like the js isn't being loaded for some sections. I also don't see any errors in the console. I'll email you the dump. Thanks.

**Comment by mmikkel** [comment] 2015-09-28 18:28
Excellent – really appreciate the help on this @owldesign.

Its interesting, because regarding JS/CSS resources I actually changed things around a bit for 0.2 – I'm [now using regex patterns](https://github.com/mmikkel/Reasons-Craft/blob/master/reasons/ReasonsPlugin.php#L81) to determine whether any resources should load for any given URL (e.g. any URL having to do with entry type editing should load the FLD class etc). It might be that my patterns are a bit off – can you copy paste whatever's in the address bar when the JS doesn't load for you?

**Comment by owldesign** [comment] 2015-09-28 19:06
Here you go.

For this url the js loads `http://craft.dev/admin/settings/sections/9/entrytypes/10`
Not for this `http://craft.dev/admin/settings/sections/11/entrytypes/12`

**Comment by owldesign** [comment] 2015-09-28 19:08
Oh I think it has something to do with the section id's. When section id 1-9 it works but when it gets into double digits it doesn't!

**Comment by mmikkel** [comment] 2015-09-28 20:21
Ah man. Blame me and my child-like regex. Thanks a lot, fixing this ASAP!

**Comment by mmikkel** [comment] 2015-09-28 20:49
This should be fixed in 0.2.1. Thanks again @owldesign!

**Closed as completed by mmikkel** 2015-09-28 20:49 UTC
Labels: bug
