### ISSUE TITLE
Asset field not triggering Reasons inside Neo blocks

### ISSUE THREAD

**Issue by artmem** [mmikkel/Reasons-Craft#29] opened 2016-09-16 03:43 UTC
I'm using reasons in a neo field. I have an asset field, and then a caption field that is set to show when the asset field is not empty, but it isn't working. The field remains hidden, whether or not the asset field is in use.

When I first tried to set it up, I couldn't -- it said there were no toggle fields. I then added a lightswitch to my field layout, and then I was able to set up the conditional, using the asset field, but it didn't work. If i change the conditional to have the lightswitch trigger the other fields, it works fine.

I'm running Craft 2.6.2931.

**Comment by mmikkel** [comment] 2016-09-16 07:39
Hi @artmem, thanks for contributing! Unfortunately, I'm not able to reproduce your issue (I've tested with an Assets field + a PlainText field, both in a regular Entries field layout and inside a Neo block). I've got some follow-up questions for you, though:

Which versions of Reasons and Neo are you currently running?
Are you seeing any JavaScript errors in your browser's dev tools console?
Which browser and OS are you using?

**Comment by mmikkel** [comment] 2016-09-16 08:46
Scratch that, I am seeing an issue with Assets (probably all relational fields/element selects) inside Neo blocks. It appears to be isolated to Neo, though – not seeing any issues with Assets fields in regular field layouts.

**Comment by benjamminf** [comment] 2016-09-16 23:32
I think it's fair to say this is a bug with Neo. I'm looking into it right now...

**Comment by benjamminf** [comment] 2016-09-17 01:53
Okay so I've determined the problem, and have come up with a working solution in Neo. Will be fixed in the next release :+1:

**Comment by mmikkel** [comment] 2016-09-17 07:17
Awesome, @benjamminf – thanks a lot!

**Comment by stephanedemotte** [comment] 2016-09-20 11:25
@benjamminf do you have a release date for the fix ?
Thanks you !

**Comment by benjamminf** [comment] 2016-09-20 11:47
No worries @stephanedemotte - new version of Neo will very likely be released by the end of the week

**Comment by stephanedemotte** [comment] 2016-09-20 12:36
Great thanks !

**Comment by artmem** [comment] 2016-10-07 16:30
@benjamminf is that neo update still coming?

**Comment by benjamminf** [comment] 2016-10-30 06:41
> new version of Neo will very likely be released by the end of the week

Cue to over a month later.

It's "released" - you can grab a copy from the master branch. This ended up being a pretty large update - I'm still testing everything thoroughly though so I haven't created a proper release for it yet. That'll happen over the coming days probably.

**Comment by benjamminf** [comment] 2016-10-30 06:42
@mmikkel Feel free to close this now 👍

**Closed as completed** 2016-11-19 15:10 UTC
Labels: bug
